version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: bears_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_chingu
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  next:
    build: .
    container_name: bears_next
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
